export default {
 "login": "arvinxx",
  "id": 28616219,
  "node_id": "MDQ6VXNlcjI4NjE2MjE5",
  "avatar_url": "https://avatars.githubusercontent.com/u/28616219?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/arvinxx",
  "html_url": "https://github.com/arvinxx",
  "followers_url": "https://api.github.com/users/arvinxx/followers",
  "following_url": "https://api.github.com/users/arvinxx/following{/other_user}",
  "gists_url": "https://api.github.com/users/arvinxx/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/arvinxx/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/arvinxx/subscriptions",
  "organizations_url": "https://api.github.com/users/arvinxx/orgs",
  "repos_url": "https://api.github.com/users/arvinxx/repos",
  "events_url": "https://api.github.com/users/arvinxx/events{/privacy}",
  "received_events_url": "https://api.github.com/users/arvinxx/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Arvin Xu",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Design Engineer",
  "twitter_username": null,
  "public_repos": 89,
  "public_gists": 6,
  "followers": 1692,
  "following": 54,
  "created_at": "2017-05-11T04:32:22Z",
  "updated_at": "2025-04-29T09:24:01Z"
};
